channels:
  - conda-forge

dependencies:
  - boto3
  - flake8
  - hvac
  - ipykernel
  - ipywidgets
  - python-kubernetes
  - nbclient
  - nbformat
  - pip
  - pylint
  - s3fs
  - wheel
  - oauthenticator
  - keycloakauthenticator
  - requests
