channels:
  - conda-forge

dependencies:
  - beautifulsoup4
  - bokeh
  - dask
  - gensim
  - geopandas
  - jupyter-cache
  - matplotlib-base
  - mlflow
  - nltk
  - numba
  - plotly
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - xgboost
