name: Build and push jupyter images

on: push

jobs:
  jupyter-python:
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-python
      context: jupyter
      test: true
      base_image: cblefari/python-datascience
      python_version_1: 3.10.9
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  rstudio:
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: rstudio
      context: rstudio
      test: true
      base_image: cblefari/r-datascience
      r_version_1: 4.2.3
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  vscode-python:
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-python
      context: vscode
      test: true
      base_image: python-datascience
      python_version_1: 3.10.9
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}