name: Main manual workflow for Python-based image

on:
  workflow_dispatch:

env:
  PUSH: true


jobs:
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: base
      context: base
      test: true
      push: true
      base_image: ubuntu:20.04
      base_image_gpu: nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04
  python-minimal:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [base]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-minimal
      context: python-minimal
      test: false
      push: true
      base_image: inseefrlab/onyxia-base:latest
      base_image_gpu: inseefrlab/onyxia-base:latest-gpu
  python-datascience:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-datascience
      context: python-datascience
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-minimal:latest
      base_image_gpu: inseefrlab/onyxia-python-minimal:latest-gpu
  python-pytorch:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-pytorch
      context: python-pytorch
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-minimal:latest
      base_image_gpu: inseefrlab/onyxia-python-minimal:latest-gpu
  python-tensorflow:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-tensorflow
      context: python-tensorflow
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-minimal:latest
      base_image_gpu: inseefrlab/onyxia-python-minimal:latest-gpu
  pyspark:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: pyspark
      context: spark
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-minimal:latest
      base_image_gpu: inseefrlab/onyxia-python-minimal:latest-gpu
  jupyter-python:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-datascience]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-python
      context: jupyter-python
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-datascience:latest
      base_image_gpu: inseefrlab/onyxia-python-datascience:latest-gpu
  jupyter-python-pytorch:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-pytorch]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-python-pytorch
      context: jupyter-python
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-pytorch:latest
      base_image_gpu: inseefrlab/onyxia-python-pytorch:latest-gpu
  jupyter-python-tensorflow:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-tensorflow]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-python-tensorflow
      context: jupyter-python
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-tensorflow:latest
      base_image_gpu: inseefrlab/onyxia-python-tensorflow:latest-gpu
  jupyter-pyspark:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [pyspark]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-pyspark
      context: jupyter-python
      test: false
      push: true
      base_image: inseefrlab/onyxia-pyspark:latest
      base_image_gpu: inseefrlab/onyxia-pyspark:latest-gpu
  vscode-python:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-datascience]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-python
      context: vscode
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-datascience:latest
      base_image_gpu: inseefrlab/onyxia-python-datascience:latest-gpu
  vscode-python-pytorch:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-pytorch]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-python-pytorch
      context: vscode
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-pytorch:latest
      base_image_gpu: inseefrlab/onyxia-python-pytorch:latest-gpu
  vscode-python-tensorflow:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-tensorflow]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-python-tensorflow
      context: vscode
      test: false
      push: true
      base_image: inseefrlab/onyxia-python-tensorflow:latest
      base_image_gpu: inseefrlab/onyxia-python-tensorflow:latest-gpu
  vscode-pyspark:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [pyspark]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-pyspark
      context: vscode
      test: false
      push: true
      base_image: inseefrlab/onyxia-pyspark:latest
      base_image_gpu: inseefrlab/onyxia-pyspark:latest-gpu
