name: Build and push Docker images

on:
  workflow_dispatch:
  schedule:
  # every monday at 2am
    - cron: '0 1 * * 1'

jobs:
  base:
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: base
      context: base
      test: true
      base_image: ubuntu:22.04
      base_image_gpu: nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04
      external_base_image: true
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  python-minimal:
    needs: [base]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-minimal
      context: python-minimal
      test: true
      base_image: base
      python_version_1: 3.10.9
      python_version_2: 3.9.16
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  python-datascience:
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-datascience
      context: python-datascience
      test: true
      base_image: python-minimal
      python_version_1: 3.10.9
      python_version_2: 3.9.16
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  r-minimal:
    needs: [base]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: r-minimal
      context: r-minimal
      test: true
      base_image: base
      r_version_1: 4.2.3
      r_version_2: 4.1.3
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  r-datascience:
    needs: [r-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: r-datascience
      context: r-datascience
      test: true
      base_image: r-minimal
      r_version_1: 4.2.3
      r_version_2: 4.1.3
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  jupyter-python:
    needs: [python-datascience]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-python
      context: jupyter
      test: true
      base_image: python-datascience
      python_version_1: 3.10.9
      python_version_2: 3.9.16
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  vscode-python:
    needs: [python-datascience]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-python
      context: vscode
      test: true
      base_image: python-datascience
      python_version_1: 3.10.9
      python_version_2: 3.9.16
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  rstudio:
    needs: [r-datascience]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: rstudio
      context: rstudio
      test: true
      base_image: r-datascience
      r_version_1: 4.2.3
      r_version_2: 4.1.3
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  jupyter-r:
    needs: [r-datascience]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-r
      context: jupyter
      test: true
      base_image: r-datascience
      r_version_1: 4.2.3
      r_version_2: 4.1.3
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  r-python-julia:
    needs: [r-minimal]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: r-python-julia
      context: r-python-julia
      test: true
      base_image: r-minimal
      r_version_1: 4.2.3
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  vscode-r-python-julia:
    needs: [r-python-julia]
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-r-python-julia
      context: vscode
      test: true
      base_image: r-python-julia
      r_version_1: 4.2.3
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  nginx-sso:
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: nginx-sso
      context: nginx-sso
      test: false
      base_image: openresty/openresty:alpine-fat
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
