name: Main manual workflow with artefacts

on:
  workflow_dispatch:
    inputs:
      chain:
        type: choice
        description: Who to greet
        required: true
        options:
          - all
          - python
          - r
  # schedule:
  # every day at midnight for test
  # - cron: "0 0 * * *"

jobs:
  # init-variables:
  #   uses: ./.github/workflows/init-variables.yml
  # with:
  #    base_image: ubuntu:20.04
  #    base_image_gpu: nvidia/cuda:11.3.1-base-ubuntu20.04
  #    python_version: "3.10.4,3.9.13"
  #    r_version: "4.2.0,4.3.0"
  #    spark_version: "3.2.1,3.3.0"
  base:
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: base
      context: base
      test: true
      push: false
      base_image: ubuntu:20.04
      base_image_gpu: nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04
      #debug: true
  python-minimal:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    needs: [base]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: python-minimal
      context: python-minimal
      test: false
      push: false
      base_image: base
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  python-datascience:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: python-datascience
      context: python-datascience
      test: false
      push: false
      base_image: python-minimal
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  python-pytorch:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: python-pytorch
      context: python-pytorch
      test: false
      push: false
      base_image: python-minimal
      #base_image_gpu: base-gpu
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  python-tensorflow:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: python-tensorflow
      context: python-tensorflow
      test: false
      push: false
      base_image: python-minimal
      #base_image_gpu: base-gpu
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  r-minimal:
    if: ${{ inputs.chain == 'r' || inputs.chain == 'all'  }}
    needs: [base]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: r-minimal
      context: r-minimal
      test: false
      push: false
      base_image: base
      #base_image_gpu: base-gpu
      r_version_1: 4.1.2
      r_version_2: 4.2.3
  r-datascience:
    if: ${{ inputs.chain == 'r' || inputs.chain == 'all'  }}
    needs: [r-minimal]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: r-datascience
      context: r-datascience
      test: false
      push: false
      base_image: r-minimal
      #base_image_gpu: base-gpu
      r_version_1: 4.1.2
      r_version_2: 4.2.3
  jupyter:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    needs: [python-datascience]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: jupyter-python
      context: jupyter-python
      test: false
      push: false
      base_image: python-datascience
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  vscode:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    needs: [python-datascience]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: vscode-python
      context: vscode
      test: false
      push: false
      base_image: python-datascience
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  pyspark:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: pyspark
      context: spark
      test: false
      push: false
      base_image: python-minimal
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      spark_version_1: 3.2.0
      spark_version_2: 3.3.0
  jupyter-pyspark:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    needs: [pyspark]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: jupyter-pyspark
      context: jupyter-python
      test: false
      push: false
      base_image: pyspark
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      spark_version_1: 3.2.0
      spark_version_2: 3.3.0
  jupyter-pytorch:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    needs: [python-pytorch]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: jupyter-python-pytorch
      context: jupyter-python
      test: false
      push: false
      base_image: python-pytorch
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  jupyter-tensorflow:
    if: ${{ inputs.chain == 'python' || inputs.chain == 'all'  }}
    needs: [python-pytorch]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: jupyter-python-tensorflow
      context: jupyter-python
      test: false
      push: false
      base_image: python-tensorflow
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  r-studio:
    if: ${{ inputs.chain == 'r' || inputs.chain == 'all'  }}
    needs: [r-datascience]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: rstudio
      context: rstudio
      test: false
      push: false
      base_image: r-datascience
      r_version_1: 4.1.2
      r_version_2: 4.2.3
  sparkr:
    if: ${{ inputs.chain == 'r' || inputs.chain == 'all'  }}
    needs: [r-minimal]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: sparkr
      context: spark
      test: false
      push: false
      base_image: r-minimal
      r_version_1: 4.1.2
      r_version_2: 4.2.3
      spark_version_1: 3.2.0
      spark_version_2: 3.3.0
  rstudio-sparkr:
    if: ${{ inputs.chain == 'r' || inputs.chain == 'all'  }}
    needs: [sparkr]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: rstudio-sparkr
      context: rstudio
      test: false
      push: false
      base_image: sparkr
      r_version_1: 4.1.2
      r_version_2: 4.2.3
      spark_version_1: 3.2.0
      spark_version_2: 3.3.0
  jupyter-r:
    if: ${{ inputs.chain == 'r' || inputs.chain == 'all'  }}
    needs: [r-datascience]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: jupyter-r
      context: jupyter-r
      test: false
      push: false
      base_image: r-datascience
      r_version_1: 4.1.2
      r_version_2: 4.2.3
  push-release:
    if: ${{always()}}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [rstudio-sparkr, jupyter-pyspark, r-studio, vscode, jupyter]
    uses: ./.github/workflows/tag-workflow-and-push-template.yml
    with:
      prefix: onyxia
      r_version_1: 4.1.2
      r_version_2: 4.2.3
      spark_version_1: 3.2.0
      spark_version_2: 3.3.0
      python_version_1: 3.9.13
      python_version_2: 3.10.4
